=== BulaevHarry/hybris-training/Customer model extension/code/custom/customermodelext/resources/beans.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
 [y] hybris Platform

 Copyright (c) 2000-2013 hybris AG
 All rights reserved.

 This software is the confidential and proprietary information of hybris
 ("Confidential Information"). You shall not disclose such Confidential
 Information and shall use it only in accordance with the terms of the
 license agreement you entered into with hybris.


-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

	<xs:element name="beans" type="abstractPojos" />

	<xs:complexType name="abstractPojos">
		<xs:choice minOccurs="0" maxOccurs="unbounded">
			<xs:element name="bean" type="bean" />
			<xs:element name="enum" type="enum" />
		</xs:choice>
	</xs:complexType>

	<xs:complexType name="abstractPojo" abstract="true">
		<xs:attribute name="class" type="xs:string" use="required" />
		<xs:attribute name="template" type="xs:string" use="optional" />
	</xs:complexType>



	<xs:complexType name="bean">
		<xs:complexContent>
			<xs:extension base="abstractPojo">
				<xs:sequence>
					<xs:element name="description" type="xs:string" minOccurs="0" maxOccurs="1"/>
					<xs:element name="property" type="property" minOccurs="0" maxOccurs="unbounded" />
				</xs:sequence>
				<xs:attribute name="extends" type="xs:string" use="optional" />
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="property">
		<xs:sequence>
			<xs:element name="description" type="xs:string" minOccurs="0" maxOccurs="1"/>
		</xs:sequence>
		<xs:attribute name="name" type="xs:string" use="required" />
		<xs:attribute name="type" type="xs:string" use="required" />
	</xs:complexType>

	<xs:complexType name="enum">
		<xs:complexContent>
			<xs:extension base="abstractPojo">
				<xs:sequence>
					<xs:element name="description" type="xs:string" minOccurs="0" maxOccurs="1"/>
					<xs:element name="value" type="xs:string" minOccurs="1" maxOccurs="unbounded" />
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	
</xs:schema>

=== BulaevHarry/hybris-training/Customer model extension/code/custom/cme/cmefacades/resources/cmefacades-beans.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!--
 [y] hybris Platform

 Copyright (c) 2000-2013 hybris AG
 All rights reserved.

 This software is the confidential and proprietary information of hybris
 ("Confidential Information"). You shall not disclose such Confidential
 Information and shall use it only in accordance with the terms of the
 license agreement you entered into with hybris.
-->
<beans xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="beans.xsd">

 <!-- Add Telco accelerator facades specific product options -->
 <enum class="de.hybris.platform.commercefacades.product.ProductOption">
  <value>DEVICE_BUNDLE_TABS</value>
  <value>SERVICE_PLAN_BUNDLE_TABS</value>
  <value>SERVICE_ADDON_BUNDLE_TABS</value>
 </enum>

 <bean class="com.epam.cme.facades.data.DashboardBoxData">
  <property name="type" type="String" />
  <property name="active" type="boolean" />
  <property name="mainComponent" type="BundleTemplateData" />
  <property name="dashboardBoxEntries" type="java.util.List&lt;DashboardBoxEntryData>" />
 </bean>

 <bean class="com.epam.cme.facades.data.DashboardBoxEntryData">
  <property name="component" type="BundleTemplateData" />
  <property name="orderEntry" type="de.hybris.platform.commercefacades.order.data.OrderEntryData" />
 </bean>

 <bean class="com.epam.cme.facades.data.DashboardData">
  <property name="bundleNo" type="int" />
  <property name="dashboardBoxes" type="java.util.List&lt;DashboardBoxData>" />
 </bean>

 <bean class="com.epam.cme.facades.data.DashboardPopulatorParameters">
  <property name="currentComponent" type="de.hybris.platform.configurablebundleservices.model.BundleTemplateModel" />
  <property name="bundleNo" type="int" />
  <property name="cart" type="de.hybris.platform.core.model.order.CartModel" />
 </bean>

 <bean class="com.epam.cme.facades.data.BundleTemplateData">
  <property name="id" type="String" />
  <property name="name" type="String" />
  <property name="type" type="String" />
  <property name="bundleBoxes" type="java.util.List&lt;BundleBoxData>" />
  <property name="version" type="String" />
 </bean>

 <bean class="com.epam.cme.facades.data.BundleTemplateServiceAddOnsPopulatorParameters">
  <property name="currentComponent" type="de.hybris.platform.configurablebundleservices.model.BundleTemplateModel" />
  <property name="bundleNo" type="Integer" />
  <property name="cart" type="de.hybris.platform.core.model.order.CartModel" />
 </bean>

 <bean class="de.hybris.platform.commercefacades.order.data.CartData" extends="de.hybris.platform.commercefacades.order.data.AbstractOrderData">
  <property name="firstIncompleteBundleComponentsMap" type="java.util.Map&lt;Integer, com.epam.cme.facades.data.BundleTemplateData>" />
  <property name="cartInvalidMessage" type="String" />
  <property name="allEntriesCount" type="Integer" />
 </bean>

 <bean class="de.hybris.platform.commercefacades.order.data.OrderEntryData">
  <property name="bundleNo" type="int" />
  <property name="component" type="com.epam.cme.facades.data.BundleTemplateData" />
  <property name="rootBundleTemplate" type="com.epam.cme.facades.data.BundleTemplateData" />
  <property name="removeable" type="boolean" />
  <property name="editable" type="boolean" />
  <property name="valid" type="boolean" />
 </bean>

 <bean class="com.epam.cme.facades.data.BundleBoxData">
  <property name="component" type="BundleTemplateData" />
  <property name="expanded" type="boolean" />
  <property name="selectionMessage" type="String" />
  <property name="nextButton" type="boolean" />
  <property name="reviewButton" type="boolean" />
  <property name="bundleBoxEntries" type="java.util.List&lt;BundleBoxEntryData>" />
 </bean>

 <bean class="com.epam.cme.facades.data.BundleBoxEntryData">
  <property name="selected" type="boolean" />
  <property name="disabled" type="boolean" />
  <property name="removable" type="boolean" />
  <property name="product" type="de.hybris.platform.commercefacades.product.data.ProductData" />
  <property name="orderEntry" type="de.hybris.platform.commercefacades.order.data.OrderEntryData" />
  <property name="disabledMessage" type="String" />
 </bean>

 <bean class="com.epam.cme.facades.data.BundleTabData">
  <property name="parentBundleTemplate" type="BundleTemplateData" />
  <property name="sourceComponent" type="BundleTemplateData" />
  <property name="targetComponent" type="BundleTemplateData" />
  <property name="frequencyTabs" type="java.util.List&lt;FrequencyTabData>" />
  <property name="preselected" type="boolean" />
 </bean>

 <bean class="com.epam.cme.facades.data.FrequencyTabData">
  <property name="termOfServiceFrequency" type="de.hybris.platform.subscriptionfacades.data.TermOfServiceFrequencyData" />
  <property name="termOfServiceNumber" type="int" />
  <property name="products" type="java.util.List&lt;de.hybris.platform.commercefacades.product.data.ProductData>" />
  <property name="preselected" type="boolean" />
 </bean>

 <bean class="de.hybris.platform.commercefacades.product.data.ProductData">
  <property name="bundleTabs" type="java.util.List&lt;com.epam.cme.facades.data.BundleTabData>" />
  <property name="thisBundleProductPrice" type="de.hybris.platform.commercefacades.product.data.PriceData" />
  <property name="otherBundleProductPrice" type="de.hybris.platform.commercefacades.product.data.PriceData" />
  <property name="preselected" type="boolean" />
  <property name="lowestBundlePrice" type="de.hybris.platform.commercefacades.product.data.PriceData" />
  <property name="disabled" type="boolean" />
  <property name="disabledMessage" type="String" />
  <property name="soldIndividually" type="boolean" />
 </bean>

 <bean class="com.epam.cme.facades.organization.data.OrganizationData">
  <property name="code" type="Integer" />
  <property name="name" type="String" />
  <property name="phone" type="String" />
 </bean>

 <bean class="com.epam.cme.facades.user.data.CmeRegisterData" extends="de.hybris.platform.commercefacades.user.data.RegisterData">
  <property name="organizationsIds" type="java.util.List&lt;Integer>" />
 </bean>

</beans>
